### ISSUE TITLE
Dockless Dashboard: Show "All Time" Statistics

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/transportation.austintexas.io#271]
From Jacob C:

> The dashboard is working great for the monthly breakdown of trips, miles, etc., but we’re constantly being asked about all-time data. In the drop-down month selection, can we add an “All-Time” option?

**Comment by johnclary** [comment]
@mateoclarke can we prioritize this? Possibly a good one for Tyler W.

**Comment by mateoclarke** [comment]
Absolutely. I agree.
