### ISSUE TITLE
Headshots for Transportation.austintexas.io "About" page

### ISSUE THREAD

**Issue by amenity** [cityofaustin/transportation.austintexas.io#274]
We need to update team photos on the [Tansportation.austintexas.io "About Us" page](https://transportation.austintexas.io/about/). Please upload a good quality headshot [here](https://drive.google.com/open?id=1y_yhkZQE5uSRhLZAHJn2kFuXPBixVJ2G).  

- [x] Amenity
- [x] Jaime
- [x] Scott
- [x] Sergio
- [x] Mike
- [x] Billy
- [x] Surbhi
- [x] Tyler

@TracyLinder - do you have a higher-resolution version of yours?

**Comment by sergiogcx** [comment]
FYI, if you get upload permission errors, check that you are logged in using your @austintexas.gov google account.

**Comment by TracyLinder** [comment]
@dianamartin & I just had a 60 second photo shoot. Hopefully it's higher res. :)

**Comment by amenity** [comment]
Just emailed Surbhi to see if she has one. 📩
