### ISSUE TITLE
 Remove "Maintenance in Progress" Banners from Signal Requests and Signal Timing Dashboards

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/transportation.austintexas.io#293]
The socrata data issues have been resolved, so we can remove the "maintenance in progress" banners from the [Signal Timing](http://transportation.austintexas.io/signal-timing/) and [Signal Requests](http://transportation.austintexas.io/signal-requests/) dashboards. 

[Original issue](https://github.com/cityofaustin/transportation.austintexas.io/issues/263).

**Comment by mateoclarke** [comment]
This should be quick. We'll get it done this sprint.
