### ISSUE TITLE
Migrate hosting from Github Pages to Netlify

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/transportation.austintexas.io#297]
We currently host this website on Github Pages, which is great for starting off new projects quickly. GH Pages does have limitations around debugging deployment issues since it doesn't have any readable logs. It also doesn't have preview apps (temporary deployed instances of the code from Pull Requests) which Netlify does. 

We should use our team's shared Netlify account and set up a new connection to this Github repo. Login to Netlify using GitHub OAuth as `atdservicebot`. pw is in 1P. Once its working, it will host the site on a random like subdomain.netlify.com url.

Once thats working, we'll need to update the AWS DNS configuration as well so it points at the new Netlify IP. @sergiogcx (the AWS guru) or I can help once you get to that step.

**Comment by mateoclarke** [comment]
Last step is creating a `master` branch to replace the `gh-pages` branch

**Comment by sergiogcx** [comment]
This was completed last week, I showed Tyler how to make the domain changes via CNAME. He made the SSL certificate request and the switch took a few minutes and it currently works great without any mixed-content issues.
